#!/usr/bin/env python3
"""
Convert final.json to a formatted report.md for human reading.

Usage:
    python scripts/convert_to_report.py path/to/final.json

Output:
    Creates report.md in the same directory as the input JSON file.
"""

import json
import sys
from pathlib import Path
from datetime import datetime


# ── Status badge ──────────────────────────────────────────────────────────────

STATUS_BADGES = {
    "GREEN": "🟢 GREEN",
    "YELLOW": "🟡 YELLOW",
    "RED": "🔴 RED",
}


# ── Markdown rendering ───────────────────────────────────────────────────────

def render_header(meta: dict, status: str) -> str:
    """Render the report title block and metadata table."""
    drug_name = meta.get("drug_name", "Unknown")
    drug_generic = meta.get("drug_generic", "Unknown")
    company = meta.get("company", "Unknown")
    therapeutic_area = meta.get("therapeutic_area", "")
    report_date = meta.get("report_date", "")
    persona = meta.get("analyzer_persona", "Unknown")
    run_id = meta.get("run_id", "")
    runtime_instructions = meta.get("runtime_instructions")

    badge = STATUS_BADGES.get(status, status)

    lines = [
        f"# R&D Vision Report: {drug_name} ({drug_generic})",
        "",
        f"> **Status: {badge}**",
        "",
        "---",
        "",
        "## Report Metadata",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| **Drug** | {drug_name} ({drug_generic}) |",
        f"| **Company** | {company} |",
    ]

    if therapeutic_area:
        lines.append(f"| **Therapeutic Area** | {therapeutic_area} |")

    lines.extend([
        f"| **Analyst Persona** | {persona} |",
        f"| **Report Date** | {report_date} |",
        f"| **Run ID** | `{run_id}` |",
    ])

    if runtime_instructions:
        # Escape pipes in runtime instructions for markdown table
        escaped = runtime_instructions.replace("|", "\\|")
        lines.append(f"| **Runtime Instructions** | {escaped} |")

    lines.extend(["", "---", ""])
    return "\n".join(lines)


def render_summary(summary: dict) -> str:
    """Render the executive summary section."""
    status = summary.get("status", "UNKNOWN")
    content = summary.get("content", "")
    badge = STATUS_BADGES.get(status, status)

    lines = [
        "## Executive Summary",
        "",
        f"**Overall Assessment: {badge}**",
        "",
        content,
        "",
        "---",
        "",
    ]
    return "\n".join(lines)


def render_toc(sections: list) -> str:
    """Render a table of contents from section names."""
    lines = [
        "## Table of Contents",
        "",
    ]
    for i, section in enumerate(sections, 1):
        name = section.get("name", f"Section {i}")
        anchor = name.lower().replace(" ", "-").replace("&", "").replace("/", "")
        # Remove consecutive hyphens from anchor
        while "--" in anchor:
            anchor = anchor.replace("--", "-")
        anchor = anchor.strip("-")
        lines.append(f"{i}. [{name}](#{anchor})")

    lines.extend(["", "---", ""])
    return "\n".join(lines)


def render_section(section: dict, index: int) -> str:
    """Render a single analysis section with its references."""
    name = section.get("name", f"Section {index}")
    content = section.get("content", "")
    references = section.get("references", [])

    lines = [
        f"## {name}",
        "",
        content,
        "",
    ]

    if references:
        lines.append(f"### References — {name}")
        lines.append("")
        for i, ref in enumerate(references, 1):
            title = ref.get("title", "Untitled")
            url = ref.get("url", "")
            date = ref.get("date", "")

            if url:
                entry = f"{i}. [{title}]({url})"
            else:
                entry = f"{i}. {title}"

            if date:
                entry += f" ({date})"

            lines.append(entry)
        lines.append("")

    lines.extend(["---", ""])
    return "\n".join(lines)


def render_footer(meta: dict) -> str:
    """Render the report footer with generation info."""
    persona = meta.get("analyzer_persona", "Unknown")
    report_date = meta.get("report_date", "")
    run_id = meta.get("run_id", "")
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "",
        "---",
        "",
        "*This report was generated by the BMI Drug Analysis Skill.*",
        "",
        f"- **Persona**: {persona}",
        f"- **Report date**: {report_date}",
        f"- **Run ID**: `{run_id}`",
        f"- **Generated at**: {now}",
    ]
    return "\n".join(lines)


# ── Main ─────────────────────────────────────────────────────────────────────

def convert(json_path: str) -> str:
    """Convert a final.json file to markdown and write report.md alongside it."""
    json_file = Path(json_path)

    if not json_file.exists():
        print(f"Error: {json_file} does not exist.", file=sys.stderr)
        sys.exit(1)

    if not json_file.suffix == ".json":
        print(f"Error: {json_file} is not a JSON file.", file=sys.stderr)
        sys.exit(1)

    with open(json_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    meta = data.get("meta", {})
    summary = data.get("summary", {})
    sections = data.get("sections", [])
    status = summary.get("status", "UNKNOWN")

    # Build the markdown document
    parts = [
        render_header(meta, status),
        render_summary(summary),
        render_toc(sections),
    ]

    for i, section in enumerate(sections, 1):
        parts.append(render_section(section, i))

    parts.append(render_footer(meta))

    markdown = "\n".join(parts)

    # Write report.md in the same directory as the JSON file
    output_path = json_file.parent / "report.md"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(markdown)

    print(f"Report generated: {output_path}")
    return str(output_path)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python scripts/convert_to_report.py <path-to-final.json>")
        sys.exit(1)

    convert(sys.argv[1])
